name: AnnotationScript
on: [push]

jobs:
    ci:
        name: CI
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - uses: actions/setup-java@v3
              with:
                  java-version: '21-ea'
                  distribution: 'zulu'
                  cache: 'maven'
            - name: mvn
              run: mvn clean verify
