name: AnnotationScript
on: [push]

jobs:
    ci:
        name: CI
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - uses: actions/cache@v3
              with:
                  path: ~/.m2/repository
                  key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                  restore-keys: |
                    ${{ runner.os }}-maven-
            - uses: actions/setup-java@v3
              with:
                  java-version: '21-ea'
                  distribution: 'zulu'
            - name: mvn
              run: mvn clean verify
